# -*- coding: utf-8 -*-
"""Corrige el plan de Els Pins contra el estado actual (b80) y regenera las 7 fases."""
import os, re, shutil
SRC = os.environ.get('ELS_PINS_DIR') or '/mnt/user-data/uploads/yve01/_PRUEBAS_Els_Pins'
OUT = '/tmp/plan_out'
shutil.rmtree(OUT, ignore_errors=True); os.makedirs(OUT)
p = open(os.path.join(SRC, '00_PLAN_DE_PRUEBAS.html'), encoding='utf-8').read()
n_orig = len(p)


def rep(old, new, count=1):
    global p
    assert p.count(old) == count, (p.count(old), old[:90])
    p = p.replace(old, new)


# ── cabecera ─────────────────────────────────────────────────────────────────
rep('Hotel inventado (Sitges, NIF B-66432109, cadena "Cadena Llevant"). 7 fases independientes',
    '<b>Revisado el 12 de septiembre de 2026 contra el código actual (b80)</b>: cifras y pasos comprobados ejecutando cada fase con sus ficheros; lo que cambió desde la versión del 5 de septiembre va marcado con <span class="pill">b80</span>. Hotel inventado (Sitges, NIF B-66432109, cadena "Cadena Llevant"). 7 fases independientes')
rep('<li>Render borra el disco en cada deploy: haz cada fase de una sentada.',
    '<li>Todo se descarga desde el mismo sitio: el menú <b>⚙️</b> de arriba a la derecha → "Descargas", con un desplegable por apartado (AP, Cierre, F&amp;B…). Ya no hay botones de descarga sueltos dentro de las tarjetas. <span class="pill">b80</span></li>\n'
    '<li>Sin datos, cada apartado enseña el mismo estado vacío (icono, título y botón "Procesar archivos") y los tiles salen en "—", no en 0 €. <span class="pill">b80</span></li>\n'
    '<li>Render borra el disco en cada deploy (hasta que actives el disco persistente): haz cada fase de una sentada.')

# ── FASE 1 ──────────────────────────────────────────────────────────────────
rep('''<span class="esp"><b>Debe pasar:</b> la foto se sube aparte con barra de progreso (Vision). En el registro: 4 líneas "✓ Factura …" (DG-2026-0812, EL-88213, BS-2026-0417, DG-2026-0819) y 2 "✓ Albarán …" (5531 y 5540). El resumen final cuenta 4 facturas y 2 albaranes. Ninguna "✗".</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> la foto se sube aparte con barra de progreso (Vision) y por eso <b>no</b> cuenta en el resumen del lote. En el registro del lote: 3 líneas "✓ AP <i>fichero</i>: <i>proveedor</i> — <i>total</i>" (DG-2026-0812 — 704,00 €; EL-88213 — 1.175,80 € seguido de "⚠ EL-88213: IVA al 21 % sobre 980,00 € serian 205,80 €, no 195,80 €"; DG-2026-0819 — 462,00 €) y 2 "✓ Albarán 5531 · Distribucions Garraf SL · 5 línea(s) — 640,00 €" / "✓ Albarán 5540 · … · 3 línea(s) — 385,50 €". Resumen: <b>"✅ 3 facturas AP · 2 albaranes"</b>. Después, solo, el cierre del lote: "Cruzando facturas con albaranes… ⚠ Cruce con albaranes: 1 factura(s) con incidencia de albarán: DG-2026-0819 (diferencia de importe con el albarán)" y "✓ Cuentas y asientos asignados". La foto acaba como "BS-2026-0417 — 375,10 €". Ninguna "✗". <span class="pill">b80</span></span></li>''')
rep('''(si la IA lee mal un dígito, es hallazgo de Vision).</span>''',
    '''(si la IA lee mal un dígito, es hallazgo de Vision). La EL-88213 lleva el badge rojo <b>"base + IVA ≠ total"</b> (ver paso 4). <span class="pill">b80</span></span>''')
rep('''<span class="esp"><b>Debe pasar:</b> DG-2026-0812 → <b>MATCH_ALBARAN_OK</b> ("1 albarán 5531 cuadra (0,00 % de diferencia) · mismo proveedor, entrega del 11/08/2026"). DG-2026-0819 → <b>DIFERENCIA_IMPORTE</b>: "la factura cobra <b>34,50 EUR MÁS</b> de lo entregado: base 420,00 vs albaranes 385,50 (5540)". Energía y lavandería → <b>NO_REQUIERE_ALBARAN</b> ("servicio o suministro: no lleva albarán") y <b>no</b> aparecen en "Reclamar al proveedor"; ahí solo está la DG-2026-0819.</span>
<span class="esp"><b>Tarjeta "Albaranes de entrega"</b> (debajo, en AP): 2 albaranes, 5531 "Facturado · DG-2026-0812" y 5540 "Facturado · DG-2026-0819"; al pulsar la fila se ven las líneas (5531: 5 líneas, 640,00; 5540: 3 líneas, 385,50). Excel con dos hojas.</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> en la columna Estado de la tabla: DG-2026-0812 → badge <b>MATCH_ALBARAN_OK</b>; DG-2026-0819 → badge <b>DIFERENCIA_IMPORTE</b>; Energía → <b>Sin albarán</b> (NO_REQUIERE_ALBARAN); la foto de la lavandería se queda en "Pendiente" hasta el siguiente lote (su cierre no cruza albaranes). El texto del cruce está en la tarjeta <b>"Reclamar al proveedor"</b>, donde solo aparece la DG-2026-0819: "la factura cobra <b>34.50 EUR MÁS</b> de lo entregado: base 420.00 vs albaranes 385.50 (5540) · la factura menciona el albarán 5540" (sale con puntos, no con comas: apuntado). Energía y lavandería no están ahí. <span class="pill">b80</span></span>
<span class="esp"><b>Tarjeta "Albaranes de entrega"</b> (debajo, en AP): 2 albaranes con badge <b>Facturado</b> y detalle "facturado en DG-2026-0812" / "facturado en DG-2026-0819"; al pulsar la fila se ven las líneas (5531: 5 líneas, 640,00; 5540: 3 líneas, 385,50). Excel: menú ⚙️ → AP → <b>⬇️ Albaranes</b>, dos hojas.</span></li>''')
rep('''<span class="ojo"><b>Debe pasar:</b> Yve apunta lo impreso (IVA 195,80, total 1.175,80) y <b>no avisa</b> de que 21 % de 980 son 205,80. Hoy no comprueba la aritmética de la factura: es un hueco conocido, no un fallo de la prueba. Confirma que no lo detecta.</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> Yve apunta lo impreso (IVA 195,80, total 1.175,80) <b>y avisa</b>: badge rojo "base + IVA ≠ total" junto al número, con el detalle al pasar el ratón ("IVA al 21 % sobre 980,00 € serian 205,80 €, no 195,80 €"). No corrige la cifra: la deja como está impresa y la marca. Antes del 5 de septiembre no lo comprobaba; ahora sí. <span class="pill">b80</span></span></li>''')

# ── FASE 2 ──────────────────────────────────────────────────────────────────
rep('''<span class="esp"><b>Debe pasar:</b> 3 "✓ Factura". En AP aparecen <b>2</b> filas: la IV-0733 con 1.512,50 y UNA NC-2026-118 con el badge rojo <b>"⚠ 2 documentos con este número"</b>. "Aprobar Match OK" en lote la salta.</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> 3 "✓ AP … — 290,40 € / 1.512,50 € / 314,60 €". En AP aparecen <b>2</b> filas: la IV-0733 con 1.512,50 (cuenta 622, reparaciones) y UNA NC-2026-118 (cuenta 629) con el badge rojo <b>"2 documentos con este número"</b>. Las dos están en estado "Pendiente" (en esta carpeta no hay albaranes), así que "Aprobar Match OK" en lote no aprueba ninguna: se aprueban desde /aprobaciones-ap/. <span class="pill">b80</span></span></li>''')
rep('''La de 314,60 ya no cuenta en AP, aging (2.716,90 → sin ella), provisiones ni Oracle.''',
    '''La de 314,60 no cuenta en AP, aging, provisiones ni Oracle (tampoco contaba antes de elegir: el aging ya era <b>1.802,90</b> = 290,40 + 1.512,50, y sigue igual). <span class="pill">b80</span>''')
rep('''<li>En AP, con las dos seleccionadas (o desde <b>/aprobaciones-ap/</b>), pulsa <b>Aprobar</b>.
<span class="esp"><b>Debe pasar:</b> NC-2026-118 (314,60 ≤ 500) → <b>APROBADA</b> a la primera. IV-0733 (1.512,50 &gt; 500) → mensaje "primera firma guardada" y badge <b>1/2</b>; no está aprobada todavía.</span></li>''',
    '''<li>En <b>/aprobaciones-ap/</b>, aprueba las dos (como admin).
<span class="esp"><b>Debe pasar:</b> NC-2026-118 (290,40 ≤ 500) → <b>APROBADA</b> a la primera. IV-0733 (1.512,50 &gt; 500) → aviso "✍ Primera firma guardada: falta la de otra persona" y badge <b>"✍ 1/2 firmas · firmó admin · falta otra persona"</b>; no está aprobada todavía. <span class="pill">b80</span></span></li>''')
rep('''<span class="esp"><b>Debe pasar:</b> RECHAZADA nunca pide dos firmas. Una factura ya decidida no cambia de estado con una segunda acción del mismo tipo.</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> RECHAZADA nunca pide dos firmas: la NC-2026-118 pasa a <b>RECHAZADA</b> con esa sola acción (sí cambia de estado: es una acción distinta, y queda en el historial APROBADA por admin → RECHAZADA por fc_user). Lo que no cambia nada es repetir la <b>misma</b> acción sobre una factura ya decidida (aprobar dos veces la SG de la fase 4, por ejemplo: sigue APROBADA, sin segunda fila). <span class="pill">b80</span></span></li>''')

# ── FASE 3 ──────────────────────────────────────────────────────────────────
rep('''(Booking.com Hotel Els Pins 15%, Expedia Hotel Els Pins 18%) guardadas".</span></li>''',
    '''(Booking.com Hotel Els Pins 15.0%, Expedia Hotel Els Pins 18.0%) guardadas". Es una hoja sin cabeceras conocidas, así que antes dice "sin keyword reconocible — lo lee la IA…". <span class="pill">b80</span></span></li>''')
rep('''En "Reclamaciones OTA pendientes de aprobar" aparece Booking con esos 248,00.</span></li>''',
    '''En "Reclamaciones OTA pendientes de aprobar" aparece Booking con esos 248,00.</span>
<span class="esp"><b>Certificado de doble imposición:</b> Booking.com B.V. factura desde Países Bajos (UE), así que el certificado DI sale como <b>"no aplica"</b>, no como pendiente. Antes del 7 de septiembre Yve se lo pedía; finanzas fijó la regla: solo a OTAs de fuera de la UE con convenio (Expedia, Agoda…). Lo verás en la fase 7. <span class="pill">b80</span></span></li>''')
rep('''<span class="esp"><b>Debe pasar:</b> "✓ Factura FAC-2026-CORP-0001 emitida — €1.320" (4 noches × 2 × 150 = 1.200 + 10 % IVA). Estado "Emitida".</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> "✓ Factura FAC-2026-CORP-0001 emitida — 1.320,00 €" (4 noches × 2 × 150 = 1.200 + 10 % IVA). Estado "Emitida". El botón se llama <b>📄 Nueva factura</b> y dentro, <b>📄 Emitir</b>. <span class="pill">b80</span></span></li>''')
rep('''VM-7790 → <b>DIFERENCIA_IMPORTE</b>: "factura 462,00 vs bono 480,00 (dif −18,00)".</span></li>''',
    '''VM-7790 → <b>DIFERENCIA_IMPORTE</b>: "factura 462.00 vs bono 480.00 (dif -18.00)" (con puntos: apuntado como retoque). Los dos bonos salen "Facturado" (estado de la factura) y el resumen dice 1 CUADRA · 1 DIFERENCIA_IMPORTE · 18,00 € en disputa. <span class="pill">b80</span></span></li>''')

# ── FASE 4 ──────────────────────────────────────────────────────────────────
rep('''<li>⚡ Procesar los 2 PDF. En AP tienen que estar con 423,50 y 890,00 (esta última con IVA 0).</li>''',
    '''<li>⚡ Procesar los 2 PDF. En AP tienen que estar con 423,50 (cuenta 623, servicios profesionales) y 890,00 (cuenta 625, seguros; IVA 0). <span class="pill">b80</span></li>''')
rep('''<span class="esp"><b>Debe pasar:</b> junto al botón, el chip "simulación · sin Oracle real". En el registro: PASO 1/4 autenticación (simulada) → PASO 2/4 "2 facturas leídas, <b>2 bloqueadas</b>: Factura no aprobada por cabeza de departamento" → contabilizadas <b>0</b> → PASO 4/4 sin errores. Termina en PIPELINE_COMPLETO. <b>⬇️ Asientos GL</b> descarga un GL_INTERFACE vacío (solo cabeceras).</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> junto al botón, el chip "simulación · sin Oracle real". En el registro: PASO 1/4 autenticación (simulada) → PASO 2/4 "Facturas listas para Oracle: 0" y "<b>Facturas bloqueadas (no procesan): 2</b>" con las dos líneas "✗ SG-2026-0455: Factura no aprobada por cabeza de departamento" / "✗ AM-2026-9107: …" → "No hay facturas que contabilizar" → RESUMEN FINAL (leídas 0, bloqueadas 2). <b>No</b> llega a los pasos 3/4 y 4/4: se para ahí. Termina en PIPELINE_COMPLETO. Menú ⚙️ → AP → <b>📒 Asientos GL (Oracle)</b>: no descarga nada; responde "Sin asientos que exportar: el pipeline de Oracle no ha producido ninguno todavia". <span class="pill">b80</span></span></li>''')
rep('''<span class="esp"><b>Debe pasar:</b> 2 leídas, 0 bloqueadas, <b>2 contabilizadas</b>, importe total <b>1.313,50</b>. ⬇️ Asientos GL trae las líneas de las dos: gasto al debe (vigilancia → cuenta de seguridad/servicios, seguro → 625 o equivalente), 472 solo en la de vigilancia (73,50), y 400 al haber por el total de cada una. Nada inventado: solo estas dos.</span>''',
    '''<span class="esp"><b>Debe pasar:</b> 2 leídas, 0 bloqueadas, <b>2 contabilizadas</b>, importe total <b>1,313.50 EUR</b> (el registro de Oracle escribe los importes en formato inglés), IDs SIM-<i>fecha</i>-001 y -002. Menú ⚙️ → AP → <b>📒 Asientos GL (Oracle)</b>: hoja GL_INTERFACE con <b>5 líneas</b>: AM-2026-9107 → 625 al debe 890,00 y 400 al haber 890,00 (sin 472: exenta); SG-2026-0455 → 623 al debe 350,00, 472 al debe 73,50 y 400 al haber 423,50. Hoja "Origen" con las dos facturas. Nada inventado: solo estas dos. <span class="pill">b80</span></span>
<span class="ojo"><b>Apuntado, no es de la prueba:</b> la columna LEDGER_NAME del GL dice "Hilton Barcelona" (valor por defecto de la configuración de Oracle, que no existe en producción). Se cambiará cuando se configure el ledger real.</span>''')
rep('''<span class="ojo"><b>Debe pasar:</b> lo esperable es 0 nuevas (ya contabilizadas). Si vuelve a contabilizar 2, es un hallazgo importante (duplicaría asientos).</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> en simulación vuelve a decir "2 contabilizadas", pero con los <b>mismos</b> IDs (SIM-…-001 y -002) y el GL sigue teniendo <b>5 líneas</b>: no duplica asientos. La protección de "ya contabilizada, saltada" solo actúa con Oracle real (estado CONTABILIZADA); en simulación (CONTABILIZADA_SIM) repite la pasada. Apuntado como retoque: que el resumen diga "0 nuevas" también en simulación. Si el GL pasara a 10 líneas, eso sí sería un hallazgo. <span class="pill">b80</span></span></li>''')

# ── FASE 5 ──────────────────────────────────────────────────────────────────
rep('''<li>Pestaña <b>🍽️ F&amp;B Cost</b> → subpestaña <b>📋 Recetas</b> → <b>📋 Importar recetario</b> → <code>escandallo_recetas_els_pins.xlsx</code>.
<span class="esp"><b>Debe pasar:</b> "8 recetas importadas, 17 ingredientes" (formato "una fila por ingrediente" detectado solo). En Recetas se ven las 8 con su coste y su food cost teórico (Paella ≈ 8,6 %, Merluza ≈ 12 %…).</span></li>
<li>⚡ Procesar ventas, inventario y mermas (los 3 xlsx a la vez).
<span class="esp"><b>Debe pasar:</b> "✓ F&amp;B ventas_pos_agosto_2026.xlsx: 248 registros integrados", "✓ Inventario …: 12 items integrados", "✓ Mermas …: 6 registros integrados". Ninguno pasa por IA (van por cabeceras).</span></li>
<li>F&amp;B Cost → resumen.
<span class="esp"><b>Debe pasar:</b> ventas <b>52.563,30 €</b> · coste escandallo <b>6.617,88 €</b> · food cost teórico <b>12,6 %</b> · mermas <b>95,70 €</b> · cobertura <b>99,9 %</b> con <b>1 plato sin escandallo: "Paella marinera"</b> (64 €). Categoría con más ventas: Bebidas (≈ 25.084 €).</span>
<span class="ojo"><b>Sabido:</b> "FC real" sale igual que "FC teórico" (12,6 %): hoy se calculan igual, está en la lista de pendientes. El consumo real de verdad se ve en el paso 5.</span></li>
<li>Subpestaña <b>⚠️ Mermas</b>.
<span class="esp"><b>Debe pasar:</b> total 95,70 € por causa: caducado 49,50 · barril defectuoso 19,20 · deterioro 17,00 · rotura 10,00. La merma del 02/09 está incluida (F&amp;B Cost no filtra por mes).</span></li>''',
    '''<li>⚡ Procesar archivos → los 4 xlsx de la carpeta <b>a la vez</b> (escandallo, ventas, inventario y mermas; el recuento todavía no). Ya no existe el botón "Importar recetario": el escandallo entra por Procesar archivos como todo lo demás. <span class="pill">b80</span>
<span class="esp"><b>Debe pasar:</b> "✓ Recetas escandallo_recetas_els_pins.xlsx: 8 recetas (17 ingredientes) · total 8", "✓ F&amp;B ventas_pos_agosto_2026.xlsx: 248 registros integrados · 248 en el hotel", "✓ Inventario inventario_agosto_2026.xlsx: 12 items integrados · 12 en el hotel", "✓ Mermas mermas_agosto_2026.xlsx: 6 registros integrados · 6 en el hotel". Ninguno pasa por IA (van por cabeceras).</span>
<span class="ojo"><b>Por qué los 4 juntos:</b> el coste de cada receta sale del coste unitario del <i>inventario</i>. Si subes el escandallo solo, la subpestaña Recetas enseña food costs falsos (Paella 0,8 %, Café 0,05 %…) hasta que entra el inventario. Es un hallazgo apuntado (el importador guarda el coste de la línea como si fuera unitario); con el inventario cargado los números son los buenos.</span></li>
<li>Pestaña <b>🍽️ F&amp;B Cost</b> → subpestaña <b>📋 Recetas</b>.
<span class="esp"><b>Debe pasar:</b> 8 recetas con su coste y su food cost: Pollo al ast 13,95 % · Merluza 12,21 % · Tortilla 18,27 % · Paella Els Pins 8,68 % · Copa vino 16,29 % · Caña 14,29 % · Gin tonic 12,22 % · Café 6,22 %. FC medio 12,8 %; mejor margen Café, peor Tortilla. <span class="pill">b80</span></span></li>
<li>Subpestaña <b>📊 Resumen</b>. Pon el selector <b>Mes</b> (arriba de la pestaña) en <code>2026-08</code>: vacío significa "todo el periodo" y entonces las mermas incluyen la del 02/09. <span class="pill">b80</span>
<span class="esp"><b>Debe pasar:</b> ventas <b>52.563,30 €</b> · coste escandallo <b>6.617,88 €</b> · food cost teórico <b>12,6 %</b> · mermas <b>87,70 €</b> (95,70 € si dejas el mes vacío) · cobertura <b>99,9 %</b> con <b>1 plato sin escandallo: "Paella marinera"</b> (64 €). Categoría con más ventas: Bebidas (≈ 25.084 €).</span>
<span class="esp"><b>FC real</b> ya no es una copia del teórico: se calcula por inventario (existencias iniciales F&amp;B 3.155,00 − finales 2.229,40 = consumo real 925,60; sin compras F&amp;B del mes) y sale <b>1,8 %</b>, con "sin explicar −5.779,98". Es el dato de la carpeta, no un fallo: el inventario inventado baja mucho menos que lo que se vendió. Tras el recuento (paso 6) pasa a 1,9 %. <span class="pill">b80</span></span></li>
<li>Subpestaña <b>⚠️ Mermas</b> (con el mes en 2026-08).
<span class="esp"><b>Debe pasar:</b> total <b>87,70 €</b> por causa: caducado 49,50 · barril defectuoso 19,20 · rotura 10,00 · deterioro 9,00 (5 mermas). La del 02/09 (8,00 €, deterioro) solo entra si vacías el mes: entonces 95,70 € y deterioro 17,00. F&amp;B Cost ya filtra por mes. <span class="pill">b80</span></span></li>''')
rep('''<li>Pestaña <b>🧾 Cierre</b>, mes <code>2026-08</code>, tarjeta <b>Inventarios</b>.
<span class="esp"><b>Debe pasar:</b> 12 artículos · valor inicial 3.815,00 · valor final <b>2.680,40</b> · familias: ALIMENTOS 1.605,00 → 1.155,00 · BEBIDAS 1.286,00 → 876,40 · LICORES 264,00 → 198,00 · GUEST SUPPLIES 660,00 → 451,00. Consumo teórico F&amp;B 6.617,88 (escandallo × ventas). Asientos 610/300 por familia por la bajada de existencias.</span></li>
<li>Pulsa <b>📋 Hoja de recuento</b> (descarga) y ábrela: 12 filas con la columna "recuento" vacía. Ahora sube <code>recuento_inventario_2026-08.xlsx</code> (ya rellena) con el botón <b>📤 Subir recuento</b> que está en la cabecera de esa misma tarjeta <i>Inventarios</i> (al lado de 📋 Hoja de recuento). <span class="ojo"><b>Ojo:</b> el selector de mes de Cierre sale por defecto en el mes actual: ponlo en <code>2026-08</code> antes de subir; desde b25 el recuento se guarda con el mes elegido y un mes sin recuento propio sale SIN_DATO.</span>
<span class="esp"><b>Debe pasar:</b> "12 contados". El valor final pasa a <b>2.605,20</b> (−75,20 respecto al stock del sistema): ALIMENTOS 1.116,50 · BEBIDAS 865,00 · LICORES 189,20 · GUEST SUPPLIES 434,50. El inventario del F&amp;B Cost (subpestaña Inventario) también refleja los nuevos stocks (Pollo 40, Merluza 28,5, Gin 8,6…).</span></li>''',
    '''<li>Pestaña <b>🧾 Cierre</b>, mes <code>2026-08</code>, tarjeta <b>Inventarios de cierre</b>.
<span class="esp"><b>Debe pasar:</b> 12 artículos · valor inicial 3.815,00 · valor final <b>2.680,40</b> · familias: ALIMENTOS 1.605,00 → 1.155,00 · BEBIDAS 1.286,00 → 876,40 · LICORES 264,00 → 198,00 · GUEST SUPPLIES 660,00 → 451,00. Consumo real F&amp;B 925,60 · consumo teórico 6.617,88 (escandallo × ventas) · desviación −5.692,28 (−86 %): otra vez el dato de la carpeta, no un fallo. Asientos 610/300 por familia (ALIMENTOS 450,00 · BEBIDAS 409,60 · LICORES 66,00) y 612/328 para GUEST SUPPLIES (209,00). <span class="pill">b80</span></span></li>
<li>Menú ⚙️ → Cierre → <b>📋 Hoja de recuento (para contar)</b> (usa el mes del selector de Cierre: ponlo en <code>2026-08</code>) y ábrela: 12 filas con la columna "recuento" vacía. Ahora sube <code>recuento_inventario_2026-08.xlsx</code> (ya rellena) con <b>📤 Subir recuento (Procesar archivos)</b>, el botón de la cabecera de la tarjeta, que abre la misma ventana de Procesar archivos. El nombre del fichero lleva el mes, así que no te lo pide; si el nombre no lo llevara, la lista de subida te pediría el mes. <span class="pill">b80</span>
<span class="esp"><b>Debe pasar:</b> "✓ Recuento recuento_inventario_2026-08.xlsx: 12 articulos contados (0 nuevos) para 2026-08". El valor final pasa a <b>2.605,20</b> (−75,20 respecto al stock del sistema): ALIMENTOS 1.116,50 · BEBIDAS 865,00 · LICORES 189,20 · GUEST SUPPLIES 434,50. El inventario del F&amp;B Cost (subpestaña Inventario) también refleja los nuevos stocks (Pollo 40, Merluza 28,5, Gin 8,6…).</span></li>''')

# ── FASE 6 ──────────────────────────────────────────────────────────────────
rep('''<span class="esp"><b>Debe pasar:</b> 2 "✓ Factura", "✓ Banco extracto_banco_agosto_2026.xlsx: 12 movimientos integrados" y "✓ DRR DRR_els_pins_agosto_2026.xlsm: <b>3 día(s) procesado(s) · 1 día(s) descuadrado(s)</b>".</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> 2 "✓ AP …" (la EL-88213 con su aviso de IVA), "✓ Banco extracto_banco_agosto_2026.xlsx: 12 movimientos integrados" y "✓ DRR DRR_els_pins_agosto_2026.xlsm: <b>3 día(s) procesado(s) · 1 día(s) descuadrado(s)</b>". Resumen "✅ 2 facturas AP · 1 DRR · 1 banco". En el cierre del lote sale "ℹ 1 factura(s) de mercancía sin albarán que NO se reclaman porque el hotel todavía no registraba albaranes cuando se emitieron: DG-2026-0812": es informativo. <span class="pill">b80</span></span></li>''')
rep('''Alerta: día 30 (30/08/2026) descuadrado 120,00 €. Días 29 y 31 en balance.</span></li>''',
    '''Alerta: "Día 30: Out of Balance — diferencia 120.00 EUR". Días 29 y 31 en balance. <span class="pill">b80</span></span></li>''')
rep('''El segundo −704,00 se queda <b>pendiente</b> (la factura ya está usada): eso es el pago duplicado.</span></li>''',
    '''El segundo −704,00 se queda <b>pendiente</b> (la factura ya está usada): eso es el pago duplicado. Resultado de Conciliar: 2 conciliados, 10 pendientes.</span></li>''')
rep('''<li><b>🧾 Cierre</b>, mes 2026-08, tarjeta <b>Cuadre de banco</b>.
<span class="esp"><b>Debe pasar:</b> AR 2 movimientos''',
    '''<li><b>🧾 Cierre</b>, mes 2026-08, tarjeta <b>Cuadre de banco por pestañas</b>.
<span class="ojo"><b>Arreglado en b80:</b> con un hotel elegido y el banco en modo "una cuenta del grupo", esta tarjeta (y los asientos de banco del Cierre) salían vacíos aunque la pestaña Banco enseñara los 12 movimientos. Ahora el Cierre sigue la misma regla que Banco: solo filtra por hotel cuando el banco va por hotel. Si la ves vacía, es hallazgo.</span>
<span class="esp"><b>Debe pasar:</b> 12 movimientos, saldo 52.038,97 €. AR 2 movimientos''')
rep('''<li>Misma pestaña, tarjeta de <b>asientos y reconciliación</b>.
<span class="esp"><b>Debe pasar:</b> Debe = Haber y "cuadra". Asientos de las 2 facturas AP (600/629, 472, 400) y de los 2 movimientos conciliados (400 → 572). En la reconciliación: 400, 472 y 572 conciliado cuadran; 572 pendiente marca lo que queda sin conciliar; <b>705 con DIFERENCIA</b> frente al DRR (296.875,20) porque en esta fase no hay facturas de alojamiento: es la comprobación funcionando, no un error.</span></li>''',
    '''<li>Misma pestaña, tarjetas <b>Reconciliación de cuentas</b>, <b>Libro Diario del mes</b> y <b>Mayor del mes</b>.
<span class="esp"><b>Debe pasar:</b> 4 asientos · 10 líneas · Debe = Haber = <b>3.759,60 €</b>, "cuadra". Asientos de las 2 facturas AP (600/629, 472, 400) y de los 2 movimientos conciliados (400 → 572, "Pago EL-88213" y "Pago DG-2026-0812"). Mayor: 400 saldo 0 · 472 259,80 · 572 −1.879,80 · 600 640,00 · 629 980,00. En la reconciliación, 8 comprobaciones: <b>6 cuadran</b> (diario, 400, 472, 572 conciliado…), <b>1 pendiente</b> (572 sin conciliar: "10 movimiento(s) por 5,708.22 EUR esperan conciliacion") y <b>1 con diferencia</b>: <b>705</b> frente al DRR (296.875,20) porque en esta fase no hay facturas de alojamiento: es la comprobación funcionando, no un error. <span class="pill">b80</span></span></li>''')
rep('''<span class="esp"><b>Debe pasar:</b> checklist con estado por bloque (asientos OK, banco PENDIENTE por lo no conciliado, inventarios/inmovilizado SIN_DATO si no hiciste la fase 5, fiscal PENDIENTE). Escribe un comentario en "banco" ("pago duplicado a Garraf, pedir devolución"), guarda, recarga: sigue ahí. <b>📦 Descargar paquete</b> (botón de la propia tarjeta): Excel con varias hojas y el comentario dentro. El botón de arriba de la pestaña, "⬇️ Excel del cierre", es otro: solo lleva los asientos.</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> checklist con estado por bloque: Asientos <b>OK</b> ("4 asientos · 3.759,60 €") · Reconciliación <b>PENDIENTE</b> ("6 cuadran · 1 con diferencia · 1 pendientes") · Cuadre de banco <b>PENDIENTE</b> ("12 movimientos · 1 sin clasificar · 10 sin conciliar · saldo 52.038,97 €", 0 sin clasificar si ya asignaste la transferencia) · Provisiones, Inventarios (si no hiciste la fase 5), Inmovilizado y Aging AP <b>SIN_DATO</b> · Fiscal <b>PREPARADO</b> ("303 a compensar: -259,80 € · devengado 0,00 € · deducible 259,80 €": solo hay IVA soportado). Arriba, "Sin datos de este mes" en septiembre y nunca "Listo para la central" en agosto. Escribe un comentario en "banco" ("pago duplicado a Garraf, pedir devolución"), guarda, recarga: sigue ahí. Descargas, en el menú ⚙️ → Cierre: <b>📦 Paquete para la central</b> (Excel de 17 hojas: Portada, Checklist con el comentario, Resultados, Libro Diario, Mayor, Reconciliacion, Banco…, Modelo 303, SII…) y <b>⬇️ Excel del cierre</b>, que es otro: solo lleva los asientos. <span class="pill">b80</span></span></li>''')

# ── FASE 7 ──────────────────────────────────────────────────────────────────
rep('''<span class="esp"><b>Debe pasar:</b> 2 "✓ Factura", 2 "✓ AR … OK" (sin IA) y "✓ F&amp;B …: 3 registros integrados".</span></li>''',
    '''<span class="esp"><b>Debe pasar:</b> 2 "✓ AP … — 605,00 € / 330,00 €", 2 "✓ AR … OK" (sin IA) y "✓ F&amp;B ventas_pos_fiscal_agosto_2026.xlsx: 3 registros integrados · 3 en el hotel". Resumen "✅ 2 facturas AP · 2 informes OTA · 1 F&amp;B".</span>
<span class="esp"><b>En 📥 AR — OTAs:</b> las dos liquidaciones salen <b>SIN_TARIFA_PACTADA</b> (en esta carpeta no hay contrato; no es un fallo). Certificado DI: Booking.com → <b>no aplica</b> (UE); Expedia (Suiza, con convenio) → <b>FALTA_CERTIFICADO_DI</b>. Esa es la regla de finanzas del 7 de septiembre. <span class="pill">b80</span></span></li>''')
rep('''349: <b>1 operador</b>, Booking.com, clave S, base 1.200,00, NIF "pendiente". SII: <b>3 expedidas / 4 recibidas</b>. Estado <b>PENDIENTE</b> (faltan NIF). Avisos: casilla 67 desconocida; bienes de inversión no distinguidos.</span>''',
    '''349: <b>1 operador</b>, Booking.com, clave S, base 1.200,00, NIF pendiente (se pone en <code>config_fiscal.json → nif</code>; Expedia no va al 349 porque no es de la UE). SII: <b>3 expedidas / 4 recibidas · 2 NIF pendientes</b> (los de Booking y Expedia; las dos facturas AP ya llevan el NIF que leyó la IA: F43210987 y B60987654). Estado <b>PENDIENTE</b> (faltan esos NIF). Avisos, 5: casilla 67 desconocida; <b>"Enfoque del 303/349 validado por finanzas (7 sep 2026); los numeros de casilla NO estan verificados"</b>; bienes de inversión no distinguidos; falta el NIF-IVA de Booking; SII con 2 contrapartes sin NIF. <span class="pill">b80</span></span>''')
rep('''<li>⬇️ Excel de la tarjeta.
<span class="esp"><b>Debe pasar:</b> 5 hojas: Modelo 303, Modelo 349, SII expedidas, SII recibidas, Avisos. En "SII recibidas", Booking y Expedia con inversión del sujeto pasivo = S; las dos facturas AP con N.</span></li>''',
    '''<li>Menú ⚙️ → Cierre → <b>⬇️ Fiscal (303, 349, SII)</b>.
<span class="esp"><b>Debe pasar:</b> 5 hojas: Modelo 303, Modelo 349, SII expedidas, SII recibidas, Avisos. En "SII recibidas", Booking con clave de régimen 09 e inversión del sujeto pasivo = S; Expedia con clave 01 y S; las dos facturas AP con N y su NIF. <span class="pill">b80</span></span></li>
<li>Menú ⚙️ → Cierre → <b>📄 SII · facturas emitidas (XML AEAT)</b> y <b>📄 SII · facturas recibidas (XML AEAT)</b>.
<span class="esp"><b>Debe pasar:</b> se descargan <code>SII_emitidas_2026-08.xml</code> (3 registros TPV, F4) y <code>SII_recibidas_2026-08.xml</code> (4 registros: las 2 AP con NIF, Booking y Expedia con ISP en su bloque). Son los ficheros en el formato del SII (v1.1) para el gestor; <b>Yve no envía nada</b> a la AEAT. <span class="pill">b80</span></span></li>''')
rep('''sino "303 a ingresar: 105,00 € · devengado 643,20 · deducible 538,20".</li>''',
    '''sino "303 a ingresar: 105,00 € · devengado 643,20 € · deducible 538,20 €", con estado PENDIENTE (faltan los NIF de las OTAs) y detalle "349: 1 operadores UE, base 1.200,00 € · SII: 3 expedidas / 4 recibidas · 2 NIF pendientes". <span class="pill">b80</span></li>''')

assert len(p) > n_orig, (len(p), n_orig)
open(os.path.join(OUT, '00_PLAN_DE_PRUEBAS.html'), 'w', encoding='utf-8').write(p)

# ── las 7 fases: cabecera + intro + seccion + pie ─────────────────────────────
head = p[:p.find('<div class="toc">')]
fases = re.findall(r'<h2 id="(f\d)">(.*?)</h2>', p)
nombres = {'f1': 'fase1_AP', 'f2': 'fase2_aprobaciones', 'f3': 'fase3_AR_bonos', 'f4': 'fase4_oracle', 'f5': 'fase5_FB_inventarios', 'f6': 'fase6_banco_cierre', 'f7': 'fase7_fiscal'}
for i, (fid, _) in enumerate(fases):
    a = p.find(f'<h2 id="{fid}"')
    b = p.find(f'<h2 id="f{int(fid[1]) + 1}"') if fid != 'f7' else p.find('<h2>Qué hacer')
    sec = p[a:b]
    sec = sec[:sec.rfind('<!-- ')] if '<!-- ' in sec else sec
    html = head.replace('<title>Plan de pruebas · Hotel Els Pins</title>', f'<title>Pasos {nombres[fid]}</title>') + '<hr>\n' + sec.rstrip() + '\n</main></body></html>\n'
    os.makedirs(os.path.join(OUT, nombres[fid]), exist_ok=True)
    open(os.path.join(OUT, nombres[fid], '00_PASOS_de_esta_fase.html'), 'w', encoding='utf-8').write(html)
print('plan', n_orig, '->', len(p), 'fases', [f[0] for f in fases])
